// Idea Lab Types

export interface Question {
  id: string;
  question: string;
  questionAr: string;
  type: 'text' | 'choice' | 'multiChoice';
  options?: { value: string; label: string; labelAr: string }[];
  placeholder?: string;
  placeholderAr?: string;
  isAIGenerated?: boolean;
}

export interface UserAnswer {
  questionId: string;
  answer: string | string[];
}

export interface GeneratedIdea {
  id: string;
  title: string;
  oneLiner: string;
  description: string;
  targetUsers: string[];
  keyFeatures: string[];
  complexity: 'simple' | 'moderate' | 'complex';
  platforms: string[];
  businessModel: string;
  differentiators: string[];
  marketPotential: 'low' | 'medium' | 'high';
  techStack: string[];
  // These are optional - not shown on cards, calculated in estimate page
  estimatedCost?: {
    min: number;
    max: number;
  };
  estimatedTimeline?: {
    min: number;
    max: number;
    unit: 'days' | 'weeks' | 'months';
  };
  // Additional details for the preview modal
  problemSolved?: string;
  competitiveAdvantage?: string;
  revenueStreams?: string[];
  targetMarketSize?: string;
  successMetrics?: string[];
  challenges?: string[];
  nextSteps?: string[];
}

export interface IdeaLabState {
  currentStep: 'intro' | 'questions' | 'generating' | 'ideas' | 'details';
  currentQuestionIndex: number;
  answers: UserAnswer[];
  generatedIdeas: GeneratedIdea[];
  selectedIdea: GeneratedIdea | null;
  isLoading: boolean;
  error: string | null;
}

// First 3 fixed questions - these are always asked
export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'background',
    question: "Tell me about yourself - what's your background?",
    questionAr: "أخبرني عن نفسك - ما هي خلفيتك؟",
    type: 'choice',
    options: [
      { value: 'entrepreneur', label: 'Entrepreneur / Business Owner', labelAr: 'رائد أعمال / صاحب عمل' },
      { value: 'professional', label: 'Professional / Employee', labelAr: 'موظف / محترف' },
      { value: 'student', label: 'Student / Academic', labelAr: 'طالب / أكاديمي' },
      { value: 'creative', label: 'Creative / Freelancer', labelAr: 'مبدع / عامل حر' },
      { value: 'other', label: 'Other', labelAr: 'أخرى' }
    ]
  },
  {
    id: 'industry',
    question: "What industry or area interests you most?",
    questionAr: "ما هي الصناعة أو المجال الذي يثير اهتمامك أكثر؟",
    type: 'choice',
    options: [
      { value: 'health', label: 'Health & Wellness', labelAr: 'الصحة والعافية' },
      { value: 'finance', label: 'Finance & Banking', labelAr: 'المالية والمصارف' },
      { value: 'education', label: 'Education & Learning', labelAr: 'التعليم والتعلم' },
      { value: 'ecommerce', label: 'E-commerce & Retail', labelAr: 'التجارة الإلكترونية' },
      { value: 'logistics', label: 'Logistics & Delivery', labelAr: 'اللوجستيات والتوصيل' },
      { value: 'entertainment', label: 'Entertainment & Media', labelAr: 'الترفيه والإعلام' },
      { value: 'travel', label: 'Travel & Hospitality', labelAr: 'السفر والضيافة' },
      { value: 'realestate', label: 'Real Estate', labelAr: 'العقارات' },
      { value: 'food', label: 'Food & Restaurant', labelAr: 'الطعام والمطاعم' },
      { value: 'social', label: 'Social & Community', labelAr: 'التواصل الاجتماعي' },
      { value: 'other', label: 'Other / Multiple', labelAr: 'أخرى / متعددة' }
    ]
  },
  {
    id: 'problem',
    question: "What problem do you want to solve or what opportunity do you see?",
    questionAr: "ما هي المشكلة التي تريد حلها أو الفرصة التي تراها؟",
    type: 'text',
    placeholder: "Describe the problem or opportunity you've identified...",
    placeholderAr: "صف المشكلة أو الفرصة التي حددتها..."
  }
];

// These questions will be generated by AI based on the first 3 answers
export interface AIGeneratedQuestion {
  id: string;
  question: string;
  questionAr: string;
  type: 'text' | 'choice' | 'multiChoice';
  options?: { value: string; label: string; labelAr: string }[];
  placeholder?: string;
  placeholderAr?: string;
  isAIGenerated: true;
}
