export const PRICING_SCHEDULE = `
Use the following pricing schedule to provide accurate app development estimates:

User Authentication & Authorization > Authentication (Email) - $200 (1 day)
User Authentication & Authorization > Authentication (Phone) - $200 (1 day)
User Authentication & Authorization > Authentication (Social Media) - $200 (1 day)
User Authentication & Authorization > Multi-Factor Authentication (2FA/MFA) - $200 (1 day)
User Authentication & Authorization > Biometric Authentication > Fingerprint, Face ID - $300 (2 days)
User Authentication & Authorization > Password Reset/Recovery Flows - $100 (1 day)

User Profiles & Personalization > Customizable Profiles > Avatars, Bios, Preferences - $250 (2 days)
User Profiles & Personalization > Personalized Content Recommendations - $450 (7 days)
User Profiles & Personalization > Dark/Light Mode Themes - $200 (1 day)
User Profiles & Personalization > Language Localization > Multi-Language Support - $350 (3 days)

Navigation & Information Architecture > Intuitive Navigation > Tab Bars, Menus - $250 (2 days)
Navigation & Information Architecture > Search & Filtering Functionality > Simple - $350 (4 days)
Navigation & Information Architecture > Search & Filtering Functionality > Advanced - $700 (7 days)
Navigation & Information Architecture > Breadcrumb Navigation - $200 (2 days)
Navigation & Information Architecture > Site Maps > Especially for complex apps - $500 (5 days)
Navigation & Information Architecture > Onboarding Tutorials & Guides - $200 (3 days)

Content Management > Text Formatting > Rich Text Editors - $300 (3 days)
Content Management > Image/Video Upload & Management - $200 (2 days)
Content Management > Support for various media formats - $200 (2 days)

Social Features > User-to-User Messaging > Direct Messaging, Group Chats - $700 (6 days)
Social Features > Social Media Integration > Sharing, Login with Social Accounts - $350 (4 days)
Social Features > Activity Feeds & Notifications - $600 (5 days)
Social Features > Commenting/Review Systems - $800 (9 days)
Social Features > Community Forums - $800 (9 days)
Social Features > In-App Groups/Communities - $500 (4 days)

Offline Functionality > Data Caching for Offline Access - $850 (7 days)
Offline Functionality > Offline Forms & Data Entry - $850 (7 days)

Location-Based Services > Geolocation Tracking > User Location, Geofencing - $800 (7 days)
Location-Based Services > Maps Integration > Google Maps - $1000 (12 days)
Location-Based Services > Address Autocompletion - $500 (3 days)

Communication & Engagement > Push Notifications > Basic - $550 (4 days)
Communication & Engagement > Push Notifications > Personalized - $1,000 (9 days)
Communication & Engagement > Push Notifications > Scheduled - $800 (7 days)
Communication & Engagement > Push Notifications > Transactional - $400 (3 days)
Communication & Engagement > In-App Messaging > General - $1,000 (8 days)
Communication & Engagement > In-App Messaging > Real-Time Chat Support - $800 (7 days)
Communication & Engagement > In-App Announcements & Updates - $350 (3 days)
Communication & Engagement > Customer Feedback Forms & Surveys - $500 (4 days)
Communication & Engagement > Email Integration > Basic Setup - $200 (1 day)
Communication & Engagement > Email Integration > Automated Email Campaigns - $700 (8 days)
Communication & Engagement > Email Integration > Transactional Emails - $300 (2 days)
Communication & Engagement > SMS Integration > Basic Setup - $750 (9 days)
Communication & Engagement > SMS Integration > SMS Verification Codes - $200 (3 days)
Communication & Engagement > SMS Integration > SMS Notifications - $700 (5 days)

E-commerce & Payments > E-commerce & Payments - $1,000 (8 days)
E-commerce & Payments > Product Catalogs & Listings > General - $300 (2 days)
E-commerce & Payments > Product Catalogs & Listings > Detailed Product Descriptions - $200 (3 days)
E-commerce & Payments > Product Catalogs & Listings > High-Quality Product Images & Videos - $500 (4 days)
E-commerce & Payments > Product Catalogs & Listings > Product Reviews & Ratings - $700 (5 days)
E-commerce & Payments > Product Catalogs & Listings > Inventory Management - $700 (8 days)
E-commerce & Payments > Product Catalogs & Listings > Product Filtering & Sorting - $950 (8 days)
E-commerce & Payments > Shopping Cart & Checkout > General - $400 (3 days)
E-commerce & Payments > Shopping Cart & Checkout > Secure Checkout Process - $800 (7 days)
E-commerce & Payments > Shopping Cart & Checkout > Multiple Payment Options - $550 (7 days)
E-commerce & Payments > Shopping Cart & Checkout > Shipping Options & Calculations - $200 (2 days)
E-commerce & Payments > Shopping Cart & Checkout > Order Tracking - $300 (4 days)
E-commerce & Payments > Shopping Cart & Checkout > Coupon Codes & Discounts - $500 (4 days)
E-commerce & Payments > Subscription Management > General - $650 (7 days)
E-commerce & Payments > Subscription Management > Recurring Billing - $500 (6 days)
E-commerce & Payments > Subscription Management > Subscription Tiers - $400 (5 days)
E-commerce & Payments > Subscription Management > Subscription Renewal Reminders - $200 (2 days)
E-commerce & Payments > In-App Purchase (IAP) Integration - $1,000 (10 days)

Data & Analytics > User Analytics > Tracking User Behavior - $800 (7 days)
Data & Analytics > Performance Monitoring > App Crash Reporting - $400 (3 days)
Data & Analytics > Performance Monitoring - $800 (7 days)
Data & Analytics > A/B Testing > Testing Different UI Elements & Features - $1000 (12 days)
Data & Analytics > A/B Testing > Measuring User Engagement & Conversion Rates - $850 (6 days)

Advanced Features > Augmented Reality (AR) Integration - $2,500 (20 days)
Advanced Features > Augmented Reality (AR) Integration > AR Product Visualization - $3,000 (25 days)
Advanced Features > Virtual Reality (VR) Integration - $2,500 (20 days)
Advanced Features > Secure Data Storage - $750 (5 days)
Advanced Features > Apple Watch App Development - $1000 (10 days)
Advanced Features > Android Wear App Development - $1000 (8 days)
Advanced Features > Health Data Integration > Apple HealthKit, Google Fit - $1500 (10 days)
Advanced Features > AI-Powered Features > Personalized Recommendations - $2,500 (20 days)
Advanced Features > AI-Powered Features > Custom LLM integration for specialized Chatbot functions - $1,500 (12 days)
Advanced Features > AI-Powered Features > AI Powered image editing - $3,500 (16 days)
Advanced Features > AI-Powered Features > Natural Language Processing (NLP) - $4,000 (20 days)

Platform-Specific Features > iOS > Haptic Feedback - $250 (3 days)
Deployment > Deployment (iOS) - $450 (14 days)
Deployment > Deployment (Android) - $350 (14 days)
Deployment > Deployment (Web) - $300 (14 days)

Ready-Made App Solutions > Delivery App Solution - $10,000 (35 days)
Ready-Made App Solutions > Kindergarten Management App Solution - $8,000 (35 days)
Ready-Made App Solutions > Hypermarket Management App Solution - $15,000 (35 days)
Ready-Made App Solutions > Office Management App Solutions - $8,000 (20 days)
Ready-Made App Solutions > Gym Management App Solutions - $25,000 (60 days)
Ready-Made App Solutions > Airbnb-Style Marketplace App Solutions - $15,000 (35 days)

UI/UX Design > Comprehensive Design - $500 (10 days)
UI/UX Design > User Research > User Interviews - $1,500 (20 days)
UI/UX Design > User Research > Surveys - $1,500 (20 days)
UI/UX Design > User Research > Usability Testing - $1,000 (5 days)
UI/UX Design > User Research > Competitor Analysis - $1,500 (10 days)

When providing estimates, format costs as strings with dollar signs (e.g., "$1,000") and time as strings with days (e.g., "7 days").
`;
